apiVersion: apps/v1
kind: Deployment
metadata:
  name: cago-lab
  labels:
    app: cago-lab
    version: v1
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: cago-lab
      version: v1
  template:
    metadata:
      labels:
        app: cago-lab
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - imagePullPolicy: Always
        name: cago-lab
        image: docker.io/nginx
        resources:
          requests:
            cpu: 5m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cago-lab
  labels:
    app: cago-lab
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: cago-lab